#ddev-generated
services:
  php8.5:
    container_name: ddev-${DDEV_SITENAME}-php8.5
    restart: "no"
    # On Linux may need to to `export UID` in your environment
    # or add UID in project's .ddev/.env
    # user: "${UID}:${UID}"
    build:
      context: './php8.5-build'
      args:
        BASE_IMAGE: php:8.5.0RC1-fpm-trixie
    links:
      - db:db
    expose:
      - 9000
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - IS_DDEV_PROJECT=true
      - DDEV_PHP_VERSION=8.5
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/conf.d:/mnt/ddev_config/php
    volumes:
    - type: bind
      source: ${DDEV_APPROOT}
      target: /var/www/html
      consistency: cached
    - ".:/mnt/ddev_config:ro"
    - ddev-global-cache:/mnt/ddev-global-cache

  web:
    healthcheck:
      # Use "true" as the healthcheck to ignore its result
      test: ["CMD", "true"]