name: tests
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"

  schedule:
    - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        ddev_version: [stable, HEAD]
        bats_test: [
          "install from directory",
          "install from release",
          "web functionality with custom docroot",
          "drupal 11 installation with php85",
        ]

      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ github.repository }}
          addon_ref: ${{ github.ref }}
          test_command: bats tests --filter '${{ matrix.bats_test }}'